apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: gitlab
---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sonarqube
---

apiVersion: v1
kind: Service
metadata:
  name: bugzilla
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bugzilla
---

apiVersion: v1
kind: Service
metadata:
  name: mediawiki
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mediawiki
---

apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: nexus
---

apiVersion: v1
kind: Service
metadata:
  name: owaspzap
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: owaspzap

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce
          ports:
            - containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugzilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bugzilla
  template:
    metadata:
      labels:
        app: bugzilla
    spec:
      containers:
        - name: bugzilla
          image: dklawren/docker-bugzilla
          ports:
            - containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: mediawiki
          ports:
            - containerPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus
          ports:
            - containerPort: 8081
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: owaspzap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owaspzap
  template:
    metadata:
      labels:
        app: owaspzap
    spec:
      containers:
        - name: owaspzap
          image: owasp/zap2docker-stable
          command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0"]
          ports:
            - containerPort: 8090