version: '3'

services:

  jenkins:
    image: h1kkan/jenkins-docker:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - jenkins_home:/var/jenkins_home
    extra_hosts:
     - "staging:10.1.1.7"

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    links:
      - jenkins

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports:
      - "443:443"
      - "80:80"
    restart: always
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    links:
      - jenkins

  owaspZAP:
    image: owasp/zap2docker-stable
    container_name: owaspzap
    ports:
      - "8081:8080"
      - "8090:8090"
    entrypoint: zap-webswing.sh

  bugzilla:
    image: dklawren/docker-bugzilla
    container_name: bugzilla
    ports:
      - "82:80"
      - "5900:5900"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  mediawiki:
    image: mediawiki
    container_name: somewiki
    ports:
      - "8084:80"
    environment:
      - MEDIAWIKI__SITE_SERVER=http://localhost:8084
      - MEDIAWIKI_SITE_NAME=MediaWiki
      - MEDIAWIKI_SITE_LANG=en
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=tartans
      - MEDIAWIKI_UPDATE=false
      - MEDIAWIKI_SLEEP=0

  hubot:
    image: gillax/hubot-slack-jenkins
    container_name: hubot
    environment:
      - HUBOT_SLACK_TOKEN=REPLACE_WITH_SLACK_TOKEN
      - HUBOT_JENKINS_URL=http://172.18.0.8:8080
      - HUBOT_JENKINS_AUTH=admin:tartans
    links:
      - jenkins
    depends_on:
      - jenkins

#  selenium-hub:
#    image: selenium/hub
#    container_name: selenium_hub
#    ports:
#      - "4444:4444"
#    restart: on-failure
#
#  # Chrome node for Selenium Grid
#  chrome:
#    image: selenium/node-chrome
#    container_name: selenium_chrome_node
#    links:
#      - selenium-hub:hub
#    volumes:
#    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
#    restart: on-failure
#
#  # Firefox node for Selenium Grid
#  firefox:
#    image: selenium/node-firefox
#    container_name: selenium_firefox_node
#    environment:
#      HUB_PORT_4444_TCP_ADDR: hub
#    links:
#      - selenium-hub:hub
#    restart: on-failure

  nexus:
    image: sonatype/nexus
    container_name: sonatype_nexus
    volumes:
      - "nexus-data:/sonatype-work"
    ports:
      - "8082:8081"
    restart: on-failure
    links:
      - jenkins

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  nexus-data: {}